USE CIS31003

CREATE TABLE STAGING (Pilot_ID INT,
					   [TYPE_ID] INT,
					   Time_ID INT,
					   EMP_NUM INT,
					   MOD_CODE VARCHAR(10),
					   CHAR_DATE DATETIME,
					   CHAR_DISTANCE FLOAT(8),
					   CHAR_FUEL_GALLONS FLOAT(8),
					   REVENUE DECIMAL(6,2),
					   )

CREATE TABLE TYPE_DIM ([TYPE_ID] INT IDENTITY NOT NULL,
					   MOD_CODE VARCHAR(10),
					   MOD_NAME VARCHAR(20)
					   )

CREATE TABLE PILOT_DIM (PILOT_ID INT IDENTITY NOT NULL,
						EMP_NUM INT,
						EMP_LNAME VARCHAR(15),
						EMP_FNAME VARCHAR(15)
						)

CREATE TABLE TIME_DIM (TIME_ID INT IDENTITY NOT NULL,
					   CHAR_DATE DATETIME,
					   [MONTH] VARCHAR(10),
					   [YEAR] VARCHAR(4)
					   )

CREATE TABLE FACT (PILOT_ID INT NOT NULL,
				   [TYPE_ID] INT NOT NULL,
				   TIME_ID INT NOT NULL,
				   FUEL_USED INT,
				   DISTANCE INT,
				   REVENUE FLOAT(8)
				   )

ALTER TABLE TYPE_DIM
ADD CONSTRAINT PK_TYPE_ID PRIMARY KEY ([TYPE_ID]);

ALTER TABLE PILOT_DIM
ADD CONSTRAINT PK_PILOT_ID PRIMARY KEY (PILOT_ID);

ALTER TABLE TIME_DIM
ADD CONSTRAINT PK_TIME_ID PRIMARY KEY (TIME_ID);

ALTER TABLE FACT
ADD CONSTRAINT FK_PILOT_ID FOREIGN KEY (PILOT_ID) REFERENCES PILOT_DIM(PILOT_ID);

ALTER TABLE FACT
ADD CONSTRAINT FK_TYPE_ID FOREIGN KEY ([TYPE_ID]) REFERENCES TYPE_DIM([TYPE_ID]);

ALTER TABLE FACT 
ADD CONSTRAINT FK_TIME_ID FOREIGN KEY (TIME_ID) REFERENCES TIME_DIM(TIME_ID);

