USE CIS31003;
GO
CREATE PROCEDURE usp_populate_starschema
AS
BEGIN
	IF OBJECT_ID('FK_PILOT_ID', 'F') IS NOT NULL 
		ALTER TABLE FACT
			DROP CONSTRAINT FK_PILOT_ID;
	IF OBJECT_ID('FK_TYPE_ID', 'F') IS NOT NULL 
		ALTER TABLE FACT
			DROP CONSTRAINT FK_TYPE_ID;
	IF OBJECT_ID('FK_TIME_ID', 'F') IS NOT NULL 
		ALTER TABLE FACT
			DROP CONSTRAINT FK_TIME_ID;
	
	TRUNCATE TABLE FACT;
	TRUNCATE TABLE PILOT_DIM;
	TRUNCATE TABLE TYPE_DIM;
	TRUNCATE TABLE TIME_DIM;
	TRUNCATE TABLE STAGING;

	ALTER TABLE FACT ADD
		CONSTRAINT FK_FACT_PILOT FOREIGN KEY (PilotID) REFERENCES [DW].[PilotDimension](PilotID),
		CONSTRAINT FK_FACT_MODEL FOREIGN KEY (ModelID) REFERENCES [DW].[ModelDimension](ModelID),
		CONSTRAINT FK_FACT_TIME FOREIGN KEY (TimeID) REFERENCES [DW].[TimeDimension](TimeID);	

	INSERT INTO PILOT_DIM
		SELECT E.EMP_NUM, E.EMP_LNAME, E.EMP_FNAME, P.PIL_LICENSE, P.PIL_RATINGS, P.PIL_MED_TYPE, P.PIL_MED_DATE, P.PIL_PT135_DATE 
		FROM [AIR].[EMPLOYEE] E INNER JOIN [AIR].[PILOT] P ON E.EMP_NUM = P.EMP_NUM;
	
	INSERT INTO TYPE_DIM
		SELECT M.MOD_CODE, M.MOD_MANUFACTURER, M.MOD_NAME, M.MOD_SEATS, M.MOD_CHG_MILE
		FROM [AIR].[MODEL] M;

	INSERT INTO TIME_DIM
		SELECT DISTINCT CHAR_DATE, YEAR(CHAR_DATE), MONTH(CHAR_DATE)
		FROM [AIR].[CHARTER];


	INSERT INTO STAGING ([EMP_NUM], [MOD_CODE], [CHAR_DATE], [CHAR_DISTANCE], [CHAR_FUEL_GALLONS], [REVENUE])
		SELECT P.EMP_NUM, M.MOD_CODE, C.CHAR_DATE, SUM(C.CHAR_DISTANCE) AS [DISTANCE], SUM(C.CHAR_FUEL_GALLONS) AS [FUEL], SUM(M.MOD_CHG_MILE*C.CHAR_DISTANCE) AS REVENUE
		FROM [AIR].[CHARTER] C INNER JOIN [AIR].[CREW] CR ON C.CHAR_TRIP = CR.CHAR_TRIP
					INNER JOIN [AIR].[PILOT] P ON CR.EMP_NUM = P.EMP_NUM
					INNER JOIN [AIR].[AIRCRAFT] A ON C.AC_NUMBER = A.AC_NUMBER
					INNER JOIN [AIR].[MODEL] M ON A.MOD_CODE = M.MOD_CODE
		GROUP BY P.EMP_NUM, M.MOD_CODE, C.CHAR_DATE;

		UPDATE STAGING
		SET PILOT_ID = S.PILOT_ID, [TYPE_ID] = M.[TYPE_ID], TIME_ID = T.TIME_ID
		FROM STAGING S INNER JOIN PILOT_DIM P ON S.EMP_NUM = P.EMP_NUM
			INNER JOIN TYPE_DIM M ON S.MOD_CODE = M.MOD_CODE
			INNER JOIN TIME_DIM T ON S.CHAR_DATE = T.CHAR_DATE

	INSERT INTO FACT (PILOT_ID, [TYPE_ID], TIME_ID, FUEL_USED, DISTANCE, REVENUE)
		SELECT PILOT_ID, [TYPE_ID], TIME_ID, [CHAR_FUEL_GALLONS], [CHAR_DISTANCE], [REVENUE] 
		FROM STAGING;
END;
GO