--1)
SELECT P.EMP_LNAME, P.EMP_FNAME, SUM(DISTANCE) AS DISTANCE
FROM PILOT_DIM P INNER JOIN FACT F ON P.[Pilot_ID] = F.[Pilot_ID]
GROUP BY F.Pilot_ID, P.EMP_LNAME, P.EMP_FNAME
HAVING SUM(DISTANCE) = (SELECT TOP 1 SUM(DISTANCE)
								FROM PILOT_DIM P INNER JOIN FACT F ON P.[Pilot_ID] = F.[Pilot_ID]
								GROUP BY F.Pilot_ID, P.EMP_LNAME, P.EMP_FNAME
								ORDER BY SUM(DISTANCE) DESC
								);
--2)
SELECT P.EMP_LNAME, P.EMP_FNAME, T.CHAR_DATE, SUM(REVENUE) AS REVENUE
FROM PILOT_DIM P INNER JOIN FACT F ON P.[Pilot_ID] = F.[Pilot_ID]
	INNER JOIN TIME_DIM T ON F.Time_ID = T.Time_ID
GROUP BY F.Pilot_ID, F.Time_ID, P.EMP_LNAME, P.EMP_FNAME, T.CHAR_DATE